language: python
python:
  - 3.7
install:
  - pip install pipenv
  - pipenv install
  - pipenv install --dev
script:
  - pytest
before_deploy:
  - pip install --target dist requests
  - cp -r src/__main__.py dist
deploy:
  provider: lambda
  function_name: wackenBands
  region: eu-west-1
  runtime: python3.7
  module_name: __main__
  handler_name: get_bands
  zip: dist
  edge: true