language: python
python:
  - 3.7
install:
  - pip install pipenv
  - pipenv install
  - pipenv install --dev
script:
  - pytest
deploy:
  provider: lambda
  function_name: wackenBands
  region: eu-west-1
  zip: src
  edge: true