language: python
python:
  - 3.8
branches:
  only:
    - master

install:
  - pip install pipenv
  - pipenv install
  - pipenv install --dev
script:
  - pytest
before_deploy:
  - pip install --target dist requests
  - cp -r src dist
deploy:
  provider: lambda
  function_name: wackenBands
  region: eu-west-1
  runtime: python3.7
  module_name: src.__main__
  handler_name: get_bands_handler
  zip: dist
  timeout: 30
  edge: true