version: '3'

tasks:
  deploy-wacken:
    desc: Deploy WackenBand lambda
    deps: [build-wacken]
    dir: aws
    cmds:
    - aws s3api put-object --bucket festival-bands-deployment-bucket --key wacken.zip --body ../dist/wacken.zip --profile music-rating > /dev/null
    - aws cloudformation deploy --template-file cloudformation.yml --stack-name WackenBands --capabilities CAPABILITY_NAMED_IAM
      --parameter-overrides
      BandBucketArn=/band-bucket/arn
      BandBucketName=/band-bucket/name
      DeploymentBucketName=/festival-bands/deployment-bucket/name
      --profile music-rating
  build-wacken:
    cmds:
    - rm -rf dist
    - pipenv install
    - pip install --target dist requests
    - cp -r src dist
    - zip -r dist/wacken.zip dist