name: Test and Deploy
on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkoout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Test
        run: |
          pip install pipenv
          pipenv sync -d
          pipenv run pytest tests
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.LAMBDA_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.LAMBDA_DEPLOY_ACCESS_KEY_SECRET }}
          aws-region: eu-west-1
      - name: Deploy Lambda
        run: |
          pip install --target dist requests
          cp -r src dist
          cd dist
          zip -r ../dist.zip *
          cd ../
          aws lambda update-function-code --function-name wackenBands --zip-file fileb://dist.zip
